# Generated by Django 3.2.14 on 2022-07-10 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ('-id',), 'verbose_name': 'Подписку', 'verbose_name_plural': 'Подписки'},
        ),
    ]
